# Generated by Django 5.2.7 on 2025-11-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "business_address",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                (
                    "business_name",
                    models.CharField(max_length=225, verbose_name="업체명(상호명)"),
                ),
                (
                    "business_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="사업자등록번호"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "판매자 정보",
                "db_table": "sellers",
            },
        ),
    ]
