# Generated by Django 5.2.7 on 2025-11-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seller",
            options={"verbose_name_plural": "판매자 정보"},
        ),
        migrations.AlterField(
            model_name="seller",
            name="business_address",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="business_name",
            field=models.CharField(max_length=225, verbose_name="업체명(상호명)"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="business_number",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="사업자등록번호"
            ),
        ),
    ]
