# Generated by Django 5.2.7 on 2025-11-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_token",
        ),
    ]
