# Generated by Django 5.2.7 on 2025-11-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "business_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("business_name", models.CharField(max_length=225)),
                ("business_number", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "sellers",
            },
        ),
    ]
