# Generated by Django 5.2.7 on 2025-11-03 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("seller", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "business_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("business_name", models.CharField(max_length=225)),
                ("business_number", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sellers",
            },
        ),
    ]
