# Generated by Django 5.2.7 on 2025-11-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="seller",
        ),
        migrations.AddField(
            model_name="seller",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
