# Generated by Django 5.2.7 on 2025-11-10 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productimages",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productoptionvalue",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="옵션 카테고리",
            ),
        ),
        migrations.AddField(
            model_name="productoptionvalue",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_values",
                to="products.product",
                verbose_name="상품",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "group")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="products_pr_name_9ff0a3_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["seller_id"], name="products_pr_seller__1bcc9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productoptionvalue",
            index=models.Index(
                fields=["product"], name="products_pr_product_28b195_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productoptionvalue",
            index=models.Index(
                fields=["category"], name="products_pr_categor_7f627e_idx"
            ),
        ),
    ]
