# Generated by Django 5.2.7 on 2025-11-12 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="할인 가격",
            ),
        ),
        migrations.CreateModel(
            name="ProductStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(default=0, verbose_name="리뷰 수"),
                ),
                (
                    "sales_count",
                    models.PositiveIntegerField(default=0, verbose_name="판매 수"),
                ),
                (
                    "wish_count",
                    models.PositiveIntegerField(default=0, verbose_name="위시 수"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 통계",
                "verbose_name_plural": "상품 통계들",
                "ordering": ["-sales_count", "-review_count"],
                "indexes": [
                    models.Index(
                        fields=["sales_count"], name="products_pr_sales_c_b0ab0d_idx"
                    ),
                    models.Index(
                        fields=["review_count"], name="products_pr_review__78f5e4_idx"
                    ),
                    models.Index(
                        fields=["wish_count"], name="products_pr_wish_co_dc7df2_idx"
                    ),
                ],
            },
        ),
    ]
