# Generated by Django 5.2.7 on 2025-11-04 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_initial"),
        ("reviews", "0002_remove_review_image_url_reviewimage"),
    ]

    operations = []
