# Generated by Django 5.2.7 on 2025-11-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "위시리스트",
                "verbose_name_plural": "위시리스트 목록",
            },
        ),
        migrations.AddField(
            model_name="wishlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
