# Generated by Django 5.2.7 on 2025-11-11 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="change_reason",
        ),
    ]
