# Generated by Django 5.2.7 on 2025-11-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_address"),
        ("products", "0004_product_discount_price_productstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="options",
            field=models.ManyToManyField(
                blank=True, to="products.productoptionvalue", verbose_name="상품 옵션"
            ),
        ),
    ]
