# Generated by Django 5.2.7 on 2025-11-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "신용/체크카드"),
                    ("bank_transfer", "무통장입금"),
                    ("bank", "계좌이체"),
                ],
                max_length=50,
                null=True,
                verbose_name="결제 방법",
            ),
        ),
    ]
