# Generated by Django 5.2.7 on 2025-11-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_change_reason_orderitem_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(default="", max_length=255, verbose_name="주소"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="change_reason",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="변경 사유"
            ),
        ),
    ]
