# Generated by Django 5.2.7 on 2025-10-31 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "카테고리 그룹",
                "verbose_name_plural": "카테고리 그룹들",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="products.categorygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "카테고리",
                "verbose_name_plural": "카테고리들",
                "ordering": ["group__name", "name"],
                "unique_together": {("name", "group")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("origin", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("overseas_shipping", models.BooleanField(default=False)),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("description", models.TextField()),
                ("sold_out", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="products.category"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "상품",
                "verbose_name_plural": "상품들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 이미지",
                "verbose_name_plural": "상품 이미지들",
                "ordering": ["product_id", "image_id"],
            },
        ),
        migrations.CreateModel(
            name="ProductOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 옵션",
                "verbose_name_plural": "상품 옵션들",
                "ordering": ["product_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductOptionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                (
                    "extra_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="products.productoptions",
                    ),
                ),
            ],
            options={
                "verbose_name": "옵션 값",
                "verbose_name_plural": "옵션 값들",
                "ordering": ["option", "value"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="products_pr_name_9ff0a3_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["seller_id"], name="products_pr_seller__1bcc9b_idx"
            ),
        ),
    ]
