<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-31 10:00
=======
# Generated by Django 5.2.7 on 2025-11-01 11:11
>>>>>>> develop

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "카테고리 그룹",
                "verbose_name_plural": "카테고리 그룹들",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "상품 이미지",
                "verbose_name_plural": "상품 이미지들",
                "ordering": ["product_id", "image_id"],
            },
        ),
        migrations.CreateModel(
            name="ProductOptionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extra_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="추가 금액",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 옵션 값",
                "verbose_name_plural": "상품 옵션 값들",
                "ordering": ["product", "category"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="products.categorygroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "카테고리",
                "verbose_name_plural": "카테고리들",
                "ordering": ["group__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="상품명")),
                ("origin", models.CharField(max_length=100, verbose_name="원산지")),
<<<<<<< HEAD
=======
                ("stock", models.PositiveIntegerField(default=0, verbose_name="재고")),
>>>>>>> develop
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="가격"
                    ),
                ),
                (
                    "overseas_shipping",
                    models.BooleanField(default=False, verbose_name="해외배송 여부"),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="배송비",
                    ),
                ),
                ("description", models.TextField(verbose_name="상품설명")),
                (
<<<<<<< HEAD
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="수량"),
                ),
                (
=======
>>>>>>> develop
                    "sold_out",
                    models.BooleanField(default=False, verbose_name="품절버튼"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="products.category",
                        verbose_name="카테고리",
<<<<<<< HEAD
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="판매자",
=======
>>>>>>> develop
                    ),
                ),
            ],
            options={
                "verbose_name": "상품",
                "verbose_name_plural": "상품들",
                "ordering": ["-created_at"],
            },
        ),
    ]
