# Generated by Django 5.2.7 on 2025-10-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="수량"),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="배송비"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="상품설명"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="상품명"),
        ),
        migrations.AlterField(
            model_name="product",
            name="origin",
            field=models.CharField(max_length=100, verbose_name="원산지"),
        ),
        migrations.AlterField(
            model_name="product",
            name="overseas_shipping",
            field=models.BooleanField(default=False, verbose_name="해외배송 여부"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="가격"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sold_out",
            field=models.BooleanField(default=False, verbose_name="품절버튼"),
        ),
    ]
